[2025-05-08T07:31:43.875+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.human_review manual__2025-05-08T07:31:38.299247+00:00 [queued]>
[2025-05-08T07:31:43.879+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.human_review manual__2025-05-08T07:31:38.299247+00:00 [queued]>
[2025-05-08T07:31:43.879+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-08T07:31:43.886+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): human_review> on 2025-05-08 07:31:38.299247+00:00
[2025-05-08T07:31:43.900+0000] {standard_task_runner.py:57} INFO - Started process 227 to run task
[2025-05-08T07:31:43.903+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'human_review', 'manual__2025-05-08T07:31:38.299247+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmpu95tt645']
[2025-05-08T07:31:43.906+0000] {standard_task_runner.py:85} INFO - Job 239: Subtask human_review
[2025-05-08T07:31:43.977+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.human_review manual__2025-05-08T07:31:38.299247+00:00 [running]> on host 57d75ba4cf3d
[2025-05-08T07:31:44.049+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='human_review' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T07:31:38.299247+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T07:31:38.299247+00:00'
[2025-05-08T07:31:44.052+0000] {logging_mixin.py:154} INFO - üëÄ Checking for enough articles in review queue...
[2025-05-08T07:31:44.057+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/pymongo/synchronous/mongo_client.py:2554 UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://www.mongodb.com/docs/languages/python/pymongo-driver/current/faq/#is-pymongo-fork-safe-
[2025-05-08T07:31:44.814+0000] {logging_mixin.py:154} INFO - ‚è≥ Not enough files (0/5). Waiting.
[2025-05-08T07:31:44.815+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-08T07:31:44.834+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=lgbtq_model_pipeline, task_id=human_review, execution_date=20250508T073138, start_date=20250508T073143, end_date=20250508T073144
[2025-05-08T07:31:44.875+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-08T07:31:44.907+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
