[2025-05-08T08:13:51.671+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-08T08:13:39.037151+00:00 [queued]>
[2025-05-08T08:13:51.675+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-08T08:13:39.037151+00:00 [queued]>
[2025-05-08T08:13:51.676+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-08T08:13:51.683+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrain> on 2025-05-08 08:13:39.037151+00:00
[2025-05-08T08:13:51.692+0000] {standard_task_runner.py:57} INFO - Started process 3953 to run task
[2025-05-08T08:13:51.697+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'retrain', 'manual__2025-05-08T08:13:39.037151+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmpyqpa3sdy']
[2025-05-08T08:13:51.701+0000] {standard_task_runner.py:85} INFO - Job 257: Subtask retrain
[2025-05-08T08:13:51.725+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-08T08:13:39.037151+00:00 [running]> on host 57d75ba4cf3d
[2025-05-08T08:13:51.812+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='retrain' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T08:13:39.037151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T08:13:39.037151+00:00'
[2025-05-08T08:13:51.815+0000] {logging_mixin.py:154} INFO - üì¶ Combining data...
[2025-05-08T08:13:51.823+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/pymongo/synchronous/mongo_client.py:2554 UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://www.mongodb.com/docs/languages/python/pymongo-driver/current/faq/#is-pymongo-fork-safe-
[2025-05-08T08:13:52.501+0000] {logging_mixin.py:154} INFO - üï≥Ô∏è No new labeled data to retrain on.
[2025-05-08T08:13:52.502+0000] {python.py:194} INFO - Done. Returned value was: no_new_data
[2025-05-08T08:13:52.533+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=lgbtq_model_pipeline, task_id=retrain, execution_date=20250508T081339, start_date=20250508T081351, end_date=20250508T081352
[2025-05-08T08:13:52.558+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-08T08:13:52.580+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
