[2025-05-07T10:48:10.326+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.decide_branch manual__2025-05-07T10:46:48.626569+00:00 [queued]>
[2025-05-07T10:48:10.330+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.decide_branch manual__2025-05-07T10:46:48.626569+00:00 [queued]>
[2025-05-07T10:48:10.330+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-07T10:48:10.336+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): decide_branch> on 2025-05-07 10:46:48.626569+00:00
[2025-05-07T10:48:10.348+0000] {standard_task_runner.py:57} INFO - Started process 18842 to run task
[2025-05-07T10:48:10.351+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'decide_branch', 'manual__2025-05-07T10:46:48.626569+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmp_n4caca6']
[2025-05-07T10:48:10.353+0000] {standard_task_runner.py:85} INFO - Job 105: Subtask decide_branch
[2025-05-07T10:48:10.386+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.decide_branch manual__2025-05-07T10:46:48.626569+00:00 [running]> on host 6fdcfcafebfc
[2025-05-07T10:48:10.422+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='decide_branch' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T10:46:48.626569+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T10:46:48.626569+00:00'
[2025-05-07T10:48:10.423+0000] {logging_mixin.py:154} INFO - ðŸ¤– Evaluating model performance...
[2025-05-07T10:48:10.426+0000] {logging_mixin.py:154} INFO - ðŸ”¢ Previous Accuracy: 0.8197
[2025-05-07T10:48:10.426+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 226, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/branch_decision.py", line 27, in decide_branch
    print(f"ðŸ”¢ New Accuracy:      {new['accuracy']:.4f}")
KeyError: 'accuracy'
[2025-05-07T10:48:10.431+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lgbtq_model_pipeline, task_id=decide_branch, execution_date=20250507T104648, start_date=20250507T104810, end_date=20250507T104810
[2025-05-07T10:48:10.436+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 105 for task decide_branch ('accuracy'; 18842)
[2025-05-07T10:48:10.450+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-07T10:48:10.466+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
