[2025-05-07T03:20:33.779+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-07T03:20:26.541860+00:00 [queued]>
[2025-05-07T03:20:33.797+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-07T03:20:26.541860+00:00 [queued]>
[2025-05-07T03:20:33.797+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-07T03:20:33.803+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrain> on 2025-05-07 03:20:26.541860+00:00
[2025-05-07T03:20:33.810+0000] {standard_task_runner.py:57} INFO - Started process 2024 to run task
[2025-05-07T03:20:33.815+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'retrain', 'manual__2025-05-07T03:20:26.541860+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmpvig0gq8q']
[2025-05-07T03:20:33.819+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask retrain
[2025-05-07T03:20:33.859+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-07T03:20:26.541860+00:00 [running]> on host 6fdcfcafebfc
[2025-05-07T03:20:33.897+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='retrain' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T03:20:26.541860+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T03:20:26.541860+00:00'
[2025-05-07T03:20:33.899+0000] {logging_mixin.py:154} INFO - üì¶ Combining data...
[2025-05-07T03:20:34.153+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_246
[2025-05-07T03:20:34.153+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_247
[2025-05-07T03:20:34.154+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_245
[2025-05-07T03:20:34.154+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_249
[2025-05-07T03:20:34.155+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_248
[2025-05-07T03:20:34.155+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_244
[2025-05-07T03:20:34.156+0000] {logging_mixin.py:154} INFO - üìö Loading labeled data...
[2025-05-07T03:20:34.247+0000] {logging_mixin.py:154} INFO - üß† Preparing triplet training data...
[2025-05-07T03:20:34.772+0000] {logging_mixin.py:154} INFO - üîç Loading encoder from local cache...
[2025-05-07T03:20:35.004+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/retrain.py", line 67, in train_triplet_model
    tokenizer = AutoTokenizer.from_pretrained(HF_MODEL_PATH, local_files_only=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 939, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2197, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for '/opt/***/hf_model'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/opt/***/hf_model' is the correct path to a directory containing all relevant files for a GPT2TokenizerFast tokenizer.
[2025-05-07T03:20:35.012+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lgbtq_model_pipeline, task_id=retrain, execution_date=20250507T032026, start_date=20250507T032033, end_date=20250507T032035
[2025-05-07T03:20:35.018+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task retrain (Can't load tokenizer for '/opt/***/hf_model'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/opt/***/hf_model' is the correct path to a directory containing all relevant files for a GPT2TokenizerFast tokenizer.; 2024)
[2025-05-07T03:20:35.029+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-07T03:20:35.043+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
